displayName=Group Storage Tracker
author=Merry Gusmas
description=Tracks valuable Group Ironman storage items that have been withdrawn and not returned.
tags=bank,gim,group,items,storage
version=1.0.0
plugins=com.groupstoragetracker.GroupStorageTrackerPlugin
build=standard
